const SUPABASE_URL = "https://oicluhfdvaroqvhwfwyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_iXAoOGZ0YppBP0Y1kJf02Q_E323DzKA";
const fallbackBatches = [
  { id: "batch-1", name: "Yakeen NEET Hindi 2027", slug: "yakeen-neet-hindi-2027", locked: true },
  { id: "batch-2", name: "Yakeen NEET Hindi 2.0 2027", slug: "yakeen-neet-hindi-2-0-2027", locked: true },
  { id: "batch-3", name: "Yakeen NEET Hindi 3.0 2027", slug: "yakeen-neet-hindi-3-0-2027", locked: true }
];
const fallbackSections = (batchId) => [{ id: `${batchId}-community`, batch_id: batchId, type: "community", name: "Community" }, { id: `${batchId}-doubt`, batch_id: batchId, type: "doubt", name: "Doubt Section" }];
const fallbackPosts = {
  community: [
    { id: "demo-c1", author_name: "Doctor", initials: "DR", role: "Batch mentor", content: "Good by community 👋\nAnd everyone 🙌 God bless you 🙏❤️", created_at: new Date(Date.now() - 120000).toISOString(), likes: 8, comments_count: 1 },
    { id: "demo-c2", author_name: "shivangi", initials: "S", role: "Yakeen learner", content: "Hyy jay bro mera bhi bhut backlog hai test bhi nhi di hu", created_at: new Date(Date.now() - 300000).toISOString(), likes: 10, comments_count: 0 }
  ],
  doubt: [
    { id: "demo-d1", author_name: "Aman K.", initials: "AK", role: "Yakeen learner", content: "Physics me circular motion ka direction wala part samajh nahi aa raha. Koi simple diagram se explain karega?", created_at: new Date(Date.now() - 600000).toISOString(), likes: 4, comments_count: 2 },
    { id: "demo-d2", author_name: "Riya S.", initials: "RS", role: "Yakeen learner", content: "Plant hormones ke questions ke liye koi short revision trick bata do please.", created_at: new Date(Date.now() - 900000).toISOString(), likes: 7, comments_count: 1 }
  ]
};
let supabaseClient = null;
let currentUser = null;
let batches = [...fallbackBatches];
let activeBatchId = fallbackBatches[0].id;
let activeSectionType = "community";
let activeTab = "all";
let expanded = new Set([activeBatchId]);
let currentPosts = [];
let selectedPostId = null;
try { const { createClient } = await import("https://esm.sh/@supabase/supabase-js@2"); supabaseClient = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY); } catch (error) { console.info("Preview mode: Supabase client unavailable.", error); }
const $ = (selector) => document.querySelector(selector);
const toast = $("#toast");
const authDialog = $("#authDialog");
const postDialog = $("#postDialog");
const commentsDialog = $("#commentsDialog");
function showToast(message) { toast.textContent = message; toast.classList.add("show"); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove("show"), 2800); }
function activeBatch() { return batches.find((batch) => batch.id === activeBatchId) || batches[0]; }
function activeSection() { return fallbackSections(activeBatchId).find((section) => section.type === activeSectionType); }
function sectionName() { return activeSectionType === "doubt" ? "Doubt Section" : "Community"; }
function formatTime(value) { const minutes = Math.max(1, Math.round((Date.now() - new Date(value).getTime()) / 60000)); return minutes < 60 ? `${minutes} min ago` : `${Math.round(minutes / 60)} hr ago`; }
function renderBatchTree() { $("#batchTree").innerHTML = batches.map((batch) => { const open = expanded.has(batch.id); const active = batch.id === activeBatchId; return `<div class="batch-item ${open ? "open" : ""}"><button class="batch-head" data-toggle-batch="${batch.id}"><span class="batch-chevron">${open ? "⌄" : "›"}</span><span>${batch.name}</span><span class="batch-lock">${batch.locked ? "▣" : "✓"}</span></button>${open ? `<div class="batch-children">${fallbackSections(batch.id).map((section) => `<button class="section-link ${active && section.type === activeSectionType ? "active" : ""} ${batch.locked && !currentUser ? "locked" : ""}" data-batch="${batch.id}" data-section="${section.type}"><span class="section-icon">${section.type === "doubt" ? "?" : "♧"}</span><span>${section.name}</span>${batch.locked && !currentUser ? "<span>⌕</span>" : ""}</button>`).join("")}</div>` : ""}</div>`; }).join(""); document.querySelectorAll("[data-toggle-batch]").forEach((button) => button.addEventListener("click", () => toggleBatch(button.dataset.toggleBatch))); document.querySelectorAll("[data-batch]").forEach((button) => button.addEventListener("click", () => selectSection(button.dataset.batch, button.dataset.section))); }
function toggleBatch(batchId) { expanded.has(batchId) ? expanded.delete(batchId) : expanded.add(batchId); renderBatchTree(); }
function selectSection(batchId, sectionType) { activeBatchId = batchId; activeSectionType = sectionType; expanded.add(batchId); const batch = activeBatch(); $("#mobileBatchLabel").textContent = batch.name; if (!currentUser) { showToast("Sign in with an enrolled account to enter this batch."); openAuth(); } renderBatchTree(); renderWorkspace(); loadPosts(); }
function renderWorkspace() { const batch = activeBatch(); $("#activeBatchCrumb").textContent = batch.name; $("#activeSectionCrumb").textContent = sectionName(); $("#workspaceTitle").textContent = sectionName(); $("#sectionKicker").textContent = activeSectionType === "doubt" ? "DOUBT RESOLUTION CHANNEL" : "STUDENT DISCUSSION CHANNEL"; $("#workspaceSubtitle").textContent = activeSectionType === "doubt" ? "Ask clearly, explain kindly, and keep every doubt inside this batch." : "Share wins, ask for study tips, and help your batch move forward."; $("#railBatchName").textContent = batch.name; $("#railBatchDescription").textContent = activeSectionType === "doubt" ? "A focused space for questions and clear explanations." : "Your focused room for notes, support, and daily momentum."; $("#communityMapRow").classList.toggle("active", activeSectionType === "community"); $("#doubtMapRow").classList.toggle("active", activeSectionType === "doubt"); $("#postDialogKicker").textContent = activeSectionType === "doubt" ? "DOUBT POST" : "COMMUNITY POST"; $("#postDialogTitle").textContent = activeSectionType === "doubt" ? "Ask your batch" : "Share with your batch"; $("#postDialogSubtitle").textContent = `This post will stay inside ${batch.name} · ${sectionName()}.`; $("#feedLabel").textContent = activeSectionType === "doubt" ? "Recent doubts" : "Recent posts"; $("#accessPill").innerHTML = `<span></span> ${currentUser ? "Enrolled access" : "Preview mode"}`; $("#enrollmentBanner").style.display = currentUser ? "none" : "flex"; }
function renderPosts() { const posts = activeTab === "mine" && currentUser ? currentPosts.filter((post) => post.user_id === currentUser.id) : currentPosts; $("#postCount").textContent = currentPosts.length; if (!posts.length) { $("#postFeed").innerHTML = `<div class="empty-state">No ${activeSectionType === "doubt" ? "doubts" : "posts"} here yet. Be the first learner to start this section.</div>`; return; } $("#postFeed").innerHTML = posts.map((post, index) => `<article class="post-card"><div class="post-head"><span class="post-avatar ${index % 3 === 0 ? "av-orange" : index % 3 === 1 ? "av-green" : "av-purple"}">${post.initials || post.author_name?.slice(0,2).toUpperCase() || "GS"}</span><div class="post-byline"><strong>${post.author_name || "Learner"}</strong><small>${post.role || "Enrolled learner"} · ${formatTime(post.created_at)}</small></div><span class="post-tag ${activeSectionType === "doubt" ? "doubt" : ""}">${activeSectionType === "doubt" ? "Doubt" : "Community"}</span><button class="post-menu" aria-label="Post menu">⋮</button></div><p class="post-content">${post.content}</p><div class="post-actions"><button data-like="${post.id}">♡ ${post.likes || 0} React</button><button data-comments="${post.id}">▢ ${post.comments_count || 0} Comment</button><button data-share="${post.id}">⌁ Share</button></div></article>`).join(""); document.querySelectorAll("[data-like]").forEach((button) => button.addEventListener("click", () => { const post = currentPosts.find((item) => item.id === button.dataset.like); if (post) { post.likes = (post.likes || 0) + 1; button.textContent = `♥ ${post.likes} React`; showToast("Reaction added inside this section."); } })); document.querySelectorAll("[data-comments]").forEach((button) => button.addEventListener("click", () => openComments(button.dataset.comments))); document.querySelectorAll("[data-share]").forEach((button) => button.addEventListener("click", () => showToast("This discussion link is ready to share."))); }
function renderLocked() { $("#postFeed").innerHTML = `<div class="locked-state"><div class="lock-icon">▣</div><h3>Enrolled learners only</h3><p>This batch is private. Sign in with an account enrolled in ${activeBatch().name} to view posts, comments, and doubts.</p><button class="button button-primary" id="lockedSignIn">Sign in to continue <span>→</span></button></div>`; $("#lockedSignIn").addEventListener("click", openAuth); }
async function loadPosts() { renderWorkspace(); if (!supabaseClient || !currentUser) { currentPosts = fallbackPosts[activeSectionType]; renderPosts(); return; } const sections = await supabaseClient.from("sections").select("id,type").eq("batch_id", activeBatchId).eq("type", activeSectionType).maybeSingle(); if (sections.error || !sections.data) { currentPosts = []; renderLocked(); return; } const result = await supabaseClient.from("posts").select("*").eq("section_id", sections.data.id).order("created_at", { ascending: false }); if (result.error) { currentPosts = []; renderLocked(); return; } currentPosts = result.data || []; renderPosts(); }
function openAuth() { authDialog.showModal(); }
async function handleAuth(event) { event.preventDefault(); const status = $("#authStatus"); if (!supabaseClient) { status.textContent = "Preview mode: connect Supabase online to sign in."; return; } status.textContent = "Signing in…"; const result = await supabaseClient.auth.signInWithPassword({ email: $("#emailInput").value, password: $("#passwordInput").value }); if (result.error) { status.textContent = result.error.message; return; } currentUser = result.data.user; authDialog.close(); showToast("Signed in. Checking your enrolled batches…"); await loadAccessibleBatches(); }
async function loadAccessibleBatches() { if (!supabaseClient || !currentUser) { renderBatchTree(); renderWorkspace(); loadPosts(); return; } const result = await supabaseClient.from("batches").select("*").order("position"); if (!result.error && result.data?.length) { batches = result.data.map((batch) => ({ ...batch, locked: false })); if (!batches.some((batch) => batch.id === activeBatchId)) activeBatchId = batches[0].id; } renderBatchTree(); renderWorkspace(); await loadPosts(); }
async function openComments(postId) { selectedPostId = postId; const post = currentPosts.find((item) => item.id === postId); $("#commentsList").innerHTML = `<div class="comment-item"><strong>${post?.author_name || "Learner"}</strong><p>Replies stay isolated inside ${activeBatch().name} · ${sectionName()}.</p></div>`; if (supabaseClient && currentUser) { const result = await supabaseClient.from("comments").select("*").eq("post_id", postId).order("created_at"); if (!result.error && result.data?.length) $("#commentsList").innerHTML = result.data.map((comment) => `<div class="comment-item"><strong>${comment.author_name || "Learner"}</strong><p>${comment.content}</p></div>`).join(""); } commentsDialog.showModal(); }
async function submitComment(event) { event.preventDefault(); if (!currentUser || !supabaseClient) { showToast("Sign in with an enrolled account to comment."); openAuth(); return; } const content = $("#commentContent").value.trim(); if (!content) return; const result = await supabaseClient.from("comments").insert({ post_id: selectedPostId, user_id: currentUser.id, content }); if (result.error) { showToast(result.error.message); return; } $("#commentContent").value = ""; showToast("Reply added inside this section."); await openComments(selectedPostId); }
async function submitPost(event) { event.preventDefault(); if (!currentUser || !supabaseClient) { $("#postStatus").textContent = "Sign in with an enrolled account before posting."; return; } const sectionResult = await supabaseClient.from("sections").select("id").eq("batch_id", activeBatchId).eq("type", activeSectionType).maybeSingle(); if (sectionResult.error || !sectionResult.data) { $("#postStatus").textContent = "You are not enrolled in this batch."; return; } const content = $("#postContent").value.trim(); const result = await supabaseClient.from("posts").insert({ section_id: sectionResult.data.id, user_id: currentUser.id, content, author_name: currentUser.email?.split("@")[0] || "Learner", initials: (currentUser.email?.slice(0,2) || "GS").toUpperCase() }); if (result.error) { $("#postStatus").textContent = result.error.message; return; } $("#postContent").value = ""; postDialog.close(); showToast("Posted inside the selected section."); await loadPosts(); }
$("#collapseAll").addEventListener("click", () => { expanded.clear(); renderBatchTree(); });
$("#communityMapRow").addEventListener("click", () => selectSection(activeBatchId, "community")); $("#doubtMapRow").addEventListener("click", () => selectSection(activeBatchId, "doubt"));
$("#newPostButton").addEventListener("click", () => { if (!currentUser) return openAuth(); postDialog.showModal(); }); $("#composeButton").addEventListener("click", () => { if (!currentUser) return openAuth(); postDialog.showModal(); }); $("#bannerSignIn").addEventListener("click", openAuth); $("#profileButton").addEventListener("click", openAuth); $("#mobileProfileButton").addEventListener("click", openAuth); $("#mobileBatchButton").addEventListener("click", () => $("#sidebar").classList.toggle("mobile-open")); $("#mobileDoubtButton").addEventListener("click", () => selectSection(activeBatchId, "doubt"));
$("#closeAuth").addEventListener("click", () => authDialog.close()); $("#authForm").addEventListener("submit", handleAuth); $("#closePost").addEventListener("click", () => postDialog.close()); $("#cancelPost").addEventListener("click", () => postDialog.close()); $("#postForm").addEventListener("submit", submitPost); $("#closeComments").addEventListener("click", () => commentsDialog.close()); $("#commentForm").addEventListener("submit", submitComment); $("#notificationButton").addEventListener("click", () => showToast("Notifications for your enrolled batches are coming next.")); $("#searchButton").addEventListener("click", () => showToast("Batch search is coming next.")); $("#sortButton").addEventListener("click", () => showToast("Showing latest activity."));
document.querySelectorAll("[data-feed-tab]").forEach((tab) => tab.addEventListener("click", () => { activeTab = tab.dataset.feedTab; document.querySelectorAll("[data-feed-tab]").forEach((item) => item.classList.toggle("active", item === tab)); renderPosts(); }));
if (supabaseClient) { const { data: { session } = {} } = await supabaseClient.auth.getSession(); currentUser = session?.user || null; supabaseClient.auth.onAuthStateChange((_event, session) => { currentUser = session?.user || null; loadAccessibleBatches(); }); }
renderBatchTree(); renderWorkspace(); await loadPosts();
