const SUPABASE_URL = "https://oicluhfdvaroqvhwfwyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_iXAoOGZ0YppBP0Y1kJf02Q_E323DzKA";
const fallbackCourses = [
  { id: "physics-foundations", title: "Physics fundamentals", subtitle: "Vectors, kinematics, and the language of motion.", category: "JEE / NEET", level: "Beginner", duration: "24 lessons", price: "Free", accent: "green", glyph: "∿" },
  { id: "organic-chemistry", title: "Organic chemistry, simply", subtitle: "Build intuition before you memorise reactions.", category: "JEE / NEET", level: "Intermediate", duration: "31 lessons", price: "₹499", accent: "orange", glyph: "⌬" },
  { id: "maths-class-10", title: "Maths that makes sense", subtitle: "A calm, visual route through Class 10 maths.", category: "School", level: "Class 10", duration: "42 lessons", price: "₹299", accent: "blue", glyph: "π" },
  { id: "public-speaking", title: "Speak with confidence", subtitle: "Turn clear thoughts into words people remember.", category: "Skills", level: "All levels", duration: "12 lessons", price: "₹399", accent: "purple", glyph: "✦" },
  { id: "upsc-essentials", title: "UPSC essentials", subtitle: "Current affairs, structure, and an honest study plan.", category: "UPSC", level: "Foundation", duration: "28 lessons", price: "₹599", accent: "green", glyph: "◒" },
  { id: "biology-revision", title: "Biology revision lab", subtitle: "High-yield concepts for faster, smarter recall.", category: "JEE / NEET", level: "Revision", duration: "18 lessons", price: "Free", accent: "orange", glyph: "⌁" }
];
let supabaseClient = null; let allCourses = [...fallbackCourses]; let activeCategory = "All"; let authMode = "signin";
try { const { createClient } = await import("https://esm.sh/@supabase/supabase-js@2"); supabaseClient = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY); } catch (error) { console.info("Preview mode: Supabase client could not load.", error); }
const $ = (selector) => document.querySelector(selector); const courseGrid = $("#courseGrid"); const toast = $("#toast"); const authDialog = $("#authDialog");
function showToast(message) { toast.textContent = message; toast.classList.add("show"); window.clearTimeout(showToast.timer); showToast.timer = window.setTimeout(() => toast.classList.remove("show"), 3200); }
function courseCard(course) { return `<article class="course-card"><div class="course-cover cover-${course.accent}"><span class="cover-badge">${course.category.toUpperCase()}</span><span class="cover-glyph">${course.glyph}</span><strong class="cover-title">${course.title.replace(", ", ",<br />")}</strong></div><div class="course-content"><div class="course-meta"><span class="tag tag-green">${course.level}</span><span>${course.price}</span></div><h3>${course.title}</h3><p>${course.subtitle}</p><div class="course-bottom"><small>◷ ${course.duration}</small><button class="course-cta" data-course-id="${course.id}">View course</button></div></div></article>`; }
function renderCourses() { const query = $("#courseSearch").value.trim().toLowerCase(); const filtered = allCourses.filter((course) => { const matchesCategory = activeCategory === "All" || course.category === activeCategory; const searchable = `${course.title} ${course.subtitle} ${course.category}`.toLowerCase(); return matchesCategory && searchable.includes(query); }); courseGrid.innerHTML = filtered.length ? filtered.map(courseCard).join("") : `<div class="empty-state">No courses found yet. Try a different search.</div>`; courseGrid.querySelectorAll("[data-course-id]").forEach((button) => button.addEventListener("click", () => openCourse(button.dataset.courseId))); }
async function loadCourses() { if (!supabaseClient) return; const { data, error } = await supabaseClient.from("courses").select("*").order("featured", { ascending: false }).order("created_at", { ascending: false }); if (!error && data?.length) allCourses = data; }
async function openCourse(courseId) { const course = allCourses.find((item) => item.id === courseId); if (!course) return; const { data: { user } = {} } = supabaseClient ? await supabaseClient.auth.getUser() : { data: {} }; if (!user) { showToast("Sign in to save your learning progress."); openAuth(); return; } if (supabaseClient) { const { error } = await supabaseClient.from("enrollments").upsert({ user_id: user.id, course_id: course.id, progress: 0 }, { onConflict: "user_id,course_id" }); if (error) console.info(error); } showToast(`You’re enrolled in ${course.title}. Let’s begin!`); }
function openAuth() { authDialog.showModal(); } function closeAuth() { authDialog.close(); }
function setAuthMode(mode) { authMode = mode; const signup = mode === "signup"; $("#authTitle").textContent = signup ? "Start your learning rhythm" : "Continue your learning"; $("#authSubtitle").textContent = signup ? "Create an account and keep your progress close." : "Sign in to save your progress across devices."; $("#authSubmit").innerHTML = signup ? "Create account <span>→</span>" : "Sign in <span>→</span>"; $("#switchAuth").textContent = signup ? "Already have an account? Sign in" : "New here? Create an account"; $("#authStatus").textContent = ""; }
async function handleAuth(event) { event.preventDefault(); const email = $("#emailInput").value; const password = $("#passwordInput").value; const status = $("#authStatus"); if (!supabaseClient) { status.textContent = "Preview mode is ready. Add your Supabase connection to sign in."; return; } status.textContent = "Working…"; const result = authMode === "signup" ? await supabaseClient.auth.signUp({ email, password }) : await supabaseClient.auth.signInWithPassword({ email, password }); if (result.error) { status.textContent = result.error.message; return; } status.textContent = authMode === "signup" ? "Account created — check your email if confirmation is enabled." : "Welcome back."; showToast(authMode === "signup" ? "Your account is ready." : "Signed in successfully."); window.setTimeout(closeAuth, 900); }
async function loadSession() { if (!supabaseClient) return; const { data: { session } = {} } = await supabaseClient.auth.getSession(); updateAccount(session?.user); supabaseClient.auth.onAuthStateChange((_event, nextSession) => updateAccount(nextSession?.user)); }
function updateAccount(user) { $("#accountButton").textContent = user?.email ? user.email.slice(0, 2).toUpperCase() : "RS"; $("#accountButton").title = user?.email || "Sign in"; }
$("#courseSearch").addEventListener("input", renderCourses); $("#categoryFilters").addEventListener("click", (event) => { const button = event.target.closest("[data-category]"); if (!button) return; activeCategory = button.dataset.category; document.querySelectorAll(".filter-chip").forEach((chip) => chip.classList.toggle("active", chip === button)); renderCourses(); }); $("#accountButton").addEventListener("click", openAuth); $("#closeDialog").addEventListener("click", closeAuth); $("#switchAuth").addEventListener("click", () => setAuthMode(authMode === "signin" ? "signup" : "signin")); $("#authForm").addEventListener("submit", handleAuth); $("#resumeButton").addEventListener("click", () => { document.querySelector("#continue").scrollIntoView({ behavior: "smooth" }); showToast("Your next session is waiting."); }); $("#viewAllButton").addEventListener("click", () => document.querySelector("#courses").scrollIntoView({ behavior: "smooth" })); $("#quizButton").addEventListener("click", () => showToast("Quick quiz is coming next — keep your streak alive!")); document.querySelectorAll("[data-action=continue]").forEach((button) => button.addEventListener("click", () => showToast("Opening Motion in a plane…"))); $("#themeButton").addEventListener("click", () => { document.body.classList.toggle("warm-mode"); showToast("A little more calm, a little more focus."); });
await loadCourses(); renderCourses(); await loadSession();
